spring.application.name=UserDataRest_Validation

spring.datasource.url=jdbc:mysql://localhost:3306/UserDataRest_Validation
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

